sources:
  enml:
    enabled: true
    path: enml/olam
    source_name: olam_enml
    parser:
      _target_: linguaalayam.corpus.enml.parse
      _partial_: true
  datuk:
    enabled: true
    path: mlml/datuk
    source_name: datuk
    parser:
      _target_: linguaalayam.corpus.datuk.parse
      _partial_: true
  ekkurup:
    enabled: true
    path: enml/ekkurup.yml
    source_name: ekkurup
    parser:
      _target_: linguaalayam.corpus.ekkurup.parse
      _partial_: true

db_batch_size: 10
limit: 50
