"""initial schema

Revision ID: 1ef24e85322f
Revises: 
Create Date: 2026-04-13 15:51:45.483831

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ef24e85322f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('dictionary_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('headword', sa.Text(), nullable=False),
    sa.Column('embed_text', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(
        "uq_dictionary_entries_source_headword",
        "dictionary_entries",
        ["source", "headword"],
    )
    op.create_index('ix_dictionary_entries_embedding_hnsw', 'dictionary_entries', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_dictionary_entries_entry_type'), 'dictionary_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_dictionary_entries_headword'), 'dictionary_entries', ['headword'], unique=False)
    op.create_index(op.f('ix_dictionary_entries_source'), 'dictionary_entries', ['source'], unique=False)
    op.create_index('ix_dictionary_entries_source_headword', 'dictionary_entries', ['source', 'headword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_dictionary_entries_source_headword",
        "dictionary_entries",
    )
    op.drop_index('ix_dictionary_entries_source_headword', table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_source'), table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_headword'), table_name='dictionary_entries')
    op.drop_index(op.f('ix_dictionary_entries_entry_type'), table_name='dictionary_entries')
    op.drop_index('ix_dictionary_entries_embedding_hnsw', table_name='dictionary_entries', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('dictionary_entries')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
