"""Add created_at and embedding field

Revision ID: 7a81e174cf96
Revises: d0e4ebf54ede
Create Date: 2025-05-17 15:36:38.220810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a81e174cf96'
down_revision: Union[str, None] = 'd0e4ebf54ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alphabet_url', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('word_definition', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('word_definition', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('word_url', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_url', 'created_at')
    op.drop_column('word_definition', 'created_at')
    op.drop_column('word_definition', 'embedding')
    op.drop_column('alphabet_url', 'created_at')
    # ### end Alembic commands ###
