"""add unique constraint source headword

Revision ID: fa3eefb53b00
Revises: 1ef24e85322f
Create Date: 2026-04-14 17:29:59.951469

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'fa3eefb53b00'
down_revision: Union[str, None] = '1ef24e85322f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
